# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_Level2_Access.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_Interface(object):
    def setupUi(self, Admin_Interface):
        Admin_Interface.setObjectName("Admin_Interface")
        Admin_Interface.resize(819, 600)
        Admin_Interface.setStyleSheet("QWidget#Admin_Interface{\n"
"    background-color: #5a5c5e;\n"
"}\n"
"QWidget#Admin_Select{\n"
" color: #5a5c5e;\n"
"}\n"
"\n"
"QLabel{\n"
"    Font: 14pt \"Arial\";\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 14pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color: #577590; \n"
"}\n"
"QPushButton:hover:!pressed{\n"
"    background-color: #739bbe; \n"
"}\n"
"QToolButton{\n"
"    font: 14pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"}\n"
"QToolButton::pressed{\n"
"    background-color: #577590; \n"
"}\n"
"QToolButton:hover:!pressed{\n"
"    background-color: #739bbe; \n"
"}\n"
"\n"
"QLineEdit{\n"
"    font: 14pt \"Arial\";\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox{\n"
"    font: 14pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"    padding-left: 30px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    width: 25;\n"
"}\n"
"\n"
"QMessageBox {\n"
"    background-color: #0D1218;\n"
"    Font: 14pt \"Arial\";\n"
"}\n"
"QMessageBox QPushButton {\n"
"    font: 14pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #1e2733    ;\n"
"    border-radius: 5px;\n"
"    height: 40;\n"
"    width: 100;\n"
"}")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Admin_Interface)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Admin_Select = QtWidgets.QTabWidget(Admin_Interface)
        self.Admin_Select.setStyleSheet("QWidget {    \n"
"    background-color: #5a5c5e;\n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar {\n"
"        alignment: left;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab { \n"
"    height: 50px; \n"
"    width: 100px; \n"
"    background: \'grey\';\n"
"    background-color: #3f464d;\n"
"    alternate-background-color: rgb(159, 162, 166);\n"
"    Font: 14pt;\n"
"    color: white;\n"
"    padding: 5;\n"
"    padding-left: 5px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"\n"
"    background-color: #577590;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4  #6c6c6c,\n"
"                                stop: 0.5 #6c6c6c, stop: 1.0 #6c6c6c);\n"
"    border-color: #6c6c6c;\n"
"    border-bottom-color: #3f464d; /* same as pane color */\n"
"    color: black;\n"
"}\n"
"\n"
"")
        self.Admin_Select.setIconSize(QtCore.QSize(100, 50))
        self.Admin_Select.setObjectName("Admin_Select")
        self.Home_Tab = QtWidgets.QWidget()
        self.Home_Tab.setStyleSheet("QWidget#centralWidget{\n"
"    background-color: #5a5c5e;\n"
"}\n"
"QWidget#Base{\n"
" color: #5a5c5e;\n"
"}\n"
"\n"
"QLabel{\n"
"    Font: 14pt \"Arial\";\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 14pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color: #577590; \n"
"}\n"
"QPushButton:hover:!pressed{\n"
"    background-color: #739bbe; \n"
"}\n"
"QToolButton{\n"
"    font: 14pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"}\n"
"QToolButton::pressed{\n"
"    background-color: #577590; \n"
"}\n"
"QToolButton:hover:!pressed{\n"
"    background-color: #739bbe; \n"
"}\n"
"\n"
"QLineEdit{\n"
"    font: 14pt \"Arial\";\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox{\n"
"    font: 14pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"    padding-left: 30px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    width: 25;\n"
"}")
        self.Home_Tab.setObjectName("Home_Tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Home_Tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Home_Welcome_Message = QtWidgets.QLabel(self.Home_Tab)
        self.Home_Welcome_Message.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.Home_Welcome_Message.setObjectName("Home_Welcome_Message")
        self.verticalLayout.addWidget(self.Home_Welcome_Message)
        self.label = QtWidgets.QLabel(self.Home_Tab)
        self.label.setStyleSheet("\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(171, 171, 171);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.Home_ChangePassword_Button = QtWidgets.QPushButton(self.Home_Tab)
        self.Home_ChangePassword_Button.setMinimumSize(QtCore.QSize(412, 50))
        self.Home_ChangePassword_Button.setMaximumSize(QtCore.QSize(436, 58))
        self.Home_ChangePassword_Button.setStyleSheet("QPushButton#Home_ChangePassword_Button {\n"
"    padding: 6px;\n"
"    font: 26pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"    min-width: 10em;\n"
"}\n"
"QPushButton#Home_ChangePassword_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Home_ChangePassword_Button.setObjectName("Home_ChangePassword_Button")
        self.horizontalLayout_7.addWidget(self.Home_ChangePassword_Button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(68, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(68, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Admin_Select.addTab(self.Home_Tab, "")
        self.Search_Tab = QtWidgets.QWidget()
        self.Search_Tab.setStyleSheet("QWidget#centralWidget{\n"
"    background-color: #5a5c5e;\n"
"}\n"
"QWidget#Base{\n"
" color: #5a5c5e;\n"
"}\n"
"\n"
"QLabel{\n"
"    Font: 14pt \"Arial\";\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 14pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color: #577590; \n"
"}\n"
"QPushButton:hover:!pressed{\n"
"    background-color: #739bbe; \n"
"}\n"
"QToolButton{\n"
"    font: 14pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"}\n"
"QToolButton::pressed{\n"
"    background-color: #577590; \n"
"}\n"
"QToolButton:hover:!pressed{\n"
"    background-color: #739bbe; \n"
"}\n"
"\n"
"QLineEdit{\n"
"    font: 14pt \"Arial\";\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    padding-left: 10;\n"
"}\n"
"\n"
"QComboBox{\n"
"    font: 14pt \"Arial\";\n"
"    color: white;\n"
"    background-color: #282c30;\n"
"    border-radius: 5px;\n"
"    padding-left: 30px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    width: 25;\n"
"}")
        self.Search_Tab.setObjectName("Search_Tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Search_Tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Search_SearchAsset_Query_Button = QtWidgets.QPushButton(self.Search_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search_SearchAsset_Query_Button.sizePolicy().hasHeightForWidth())
        self.Search_SearchAsset_Query_Button.setSizePolicy(sizePolicy)
        self.Search_SearchAsset_Query_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.Search_SearchAsset_Query_Button.setMaximumSize(QtCore.QSize(186, 51))
        self.Search_SearchAsset_Query_Button.setStyleSheet("QPushButton#Search_SearchAsset_Query_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Search_SearchAsset_Query_Button:pressed {\n"
"background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Search_SearchAsset_Query_Button.setDefault(False)
        self.Search_SearchAsset_Query_Button.setObjectName("Search_SearchAsset_Query_Button")
        self.gridLayout.addWidget(self.Search_SearchAsset_Query_Button, 9, 4, 1, 1)
        self.Search_Asset_Numbers_Field = QtWidgets.QLineEdit(self.Search_Tab)
        self.Search_Asset_Numbers_Field.setMinimumSize(QtCore.QSize(250, 30))
        self.Search_Asset_Numbers_Field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Search_Asset_Numbers_Field.setObjectName("Search_Asset_Numbers_Field")
        self.gridLayout.addWidget(self.Search_Asset_Numbers_Field, 9, 2, 1, 1)
        self.Search_Reset_Fields_Button = QtWidgets.QPushButton(self.Search_Tab)
        self.Search_Reset_Fields_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.Search_Reset_Fields_Button.setMaximumSize(QtCore.QSize(186, 51))
        self.Search_Reset_Fields_Button.setStyleSheet("QPushButton#Search_Reset_Fields_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Search_Reset_Fields_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Search_Reset_Fields_Button.setObjectName("Search_Reset_Fields_Button")
        self.gridLayout.addWidget(self.Search_Reset_Fields_Button, 4, 4, 1, 1)
        self.Search_Asset_Num_From_Label = QtWidgets.QLabel(self.Search_Tab)
        self.Search_Asset_Num_From_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Search_Asset_Num_From_Label.setObjectName("Search_Asset_Num_From_Label")
        self.gridLayout.addWidget(self.Search_Asset_Num_From_Label, 9, 0, 1, 1)
        self.Search_Datetime_From = QtWidgets.QDateEdit(self.Search_Tab)
        self.Search_Datetime_From.setMinimumSize(QtCore.QSize(250, 30))
        self.Search_Datetime_From.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Search_Datetime_From.setReadOnly(False)
        self.Search_Datetime_From.setCalendarPopup(True)
        self.Search_Datetime_From.setObjectName("Search_Datetime_From")
        self.gridLayout.addWidget(self.Search_Datetime_From, 1, 2, 1, 1)
        self.Search_Datetime_To = QtWidgets.QDateEdit(self.Search_Tab)
        self.Search_Datetime_To.setMinimumSize(QtCore.QSize(250, 30))
        self.Search_Datetime_To.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Search_Datetime_To.setReadOnly(False)
        self.Search_Datetime_To.setCalendarPopup(True)
        self.Search_Datetime_To.setObjectName("Search_Datetime_To")
        self.gridLayout.addWidget(self.Search_Datetime_To, 2, 2, 1, 1)
        self.Search_Employee_ID_Label = QtWidgets.QLabel(self.Search_Tab)
        self.Search_Employee_ID_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Search_Employee_ID_Label.setObjectName("Search_Employee_ID_Label")
        self.gridLayout.addWidget(self.Search_Employee_ID_Label, 4, 0, 1, 1)
        self.Search_Employee_ID_Entry_Field = QtWidgets.QLineEdit(self.Search_Tab)
        self.Search_Employee_ID_Entry_Field.setMinimumSize(QtCore.QSize(250, 30))
        self.Search_Employee_ID_Entry_Field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Search_Employee_ID_Entry_Field.setObjectName("Search_Employee_ID_Entry_Field")
        self.gridLayout.addWidget(self.Search_Employee_ID_Entry_Field, 4, 2, 1, 1)
        self.Search_Datetime_To_Label = QtWidgets.QLabel(self.Search_Tab)
        self.Search_Datetime_To_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Search_Datetime_To_Label.setObjectName("Search_Datetime_To_Label")
        self.gridLayout.addWidget(self.Search_Datetime_To_Label, 2, 0, 1, 1)
        self.Search_Filters_Title = QtWidgets.QLabel(self.Search_Tab)
        self.Search_Filters_Title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: Bold 14pt \"MS Shell Dlg 2\";")
        self.Search_Filters_Title.setObjectName("Search_Filters_Title")
        self.gridLayout.addWidget(self.Search_Filters_Title, 0, 0, 1, 1)
        self.Search_Datetime_From_Label = QtWidgets.QLabel(self.Search_Tab)
        self.Search_Datetime_From_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Search_Datetime_From_Label.setObjectName("Search_Datetime_From_Label")
        self.gridLayout.addWidget(self.Search_Datetime_From_Label, 1, 0, 1, 1)
        self.Search_Month_By_Month_Search_Dropdown = QtWidgets.QComboBox(self.Search_Tab)
        self.Search_Month_By_Month_Search_Dropdown.setMinimumSize(QtCore.QSize(250, 30))
        self.Search_Month_By_Month_Search_Dropdown.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Search_Month_By_Month_Search_Dropdown.setObjectName("Search_Month_By_Month_Search_Dropdown")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.setItemText(0, "")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.Search_Month_By_Month_Search_Dropdown.addItem("")
        self.gridLayout.addWidget(self.Search_Month_By_Month_Search_Dropdown, 3, 2, 1, 1)
        self.Search_Month_by_Month_Label = QtWidgets.QLabel(self.Search_Tab)
        self.Search_Month_by_Month_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Search_Month_by_Month_Label.setObjectName("Search_Month_by_Month_Label")
        self.gridLayout.addWidget(self.Search_Month_by_Month_Label, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 4, 3, 1, 1)
        self.Search_UI_Message_Prompt = QtWidgets.QLabel(self.Search_Tab)
        self.Search_UI_Message_Prompt.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Search_UI_Message_Prompt.setText("")
        self.Search_UI_Message_Prompt.setObjectName("Search_UI_Message_Prompt")
        self.gridLayout.addWidget(self.Search_UI_Message_Prompt, 9, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.Search_Display_Results_Table = QtWidgets.QTableWidget(self.Search_Tab)
        self.Search_Display_Results_Table.setStyleSheet("\n"
"\n"
"QTableWidget#Search_Display_Results_Table{\n"
"    border-radius: 8;\n"
"    background-color: #3f464d;\n"
"    alternate-background-color: rgb(159, 162, 166);\n"
"    Font: 14pt;\n"
"    color: white;\n"
"    gridline-color: #1C2321;\n"
"}\n"
"\n"
"QTableView:item:selected:focus {background-color: #577590 ;}\n"
"QTableView:item:selected {background-color: #577590 ;}\n"
"\n"
"QTableView QTableCornerButton::section {\n"
"    border-top-left-radius: 8;\n"
"    background-color: #5F6366;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #282c30   ;\n"
"    color: white;\n"
"    font: Bold 14pt;\n"
"    padding: 5;\n"
"    padding-left: 5px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QHeaderView::section:checked\n"
"{\n"
"    background-color:#0D1218   ;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border-radius: 2;\n"
"}\n"
"QProgressBar::chunk{\n"
"    background-color:#53a369;\n"
"}\n"
"")
        self.Search_Display_Results_Table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Search_Display_Results_Table.setObjectName("Search_Display_Results_Table")
        self.Search_Display_Results_Table.setColumnCount(4)
        self.Search_Display_Results_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Search_Display_Results_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Search_Display_Results_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Search_Display_Results_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Search_Display_Results_Table.setHorizontalHeaderItem(3, item)
        self.Search_Display_Results_Table.horizontalHeader().setCascadingSectionResizes(False)
        self.Search_Display_Results_Table.horizontalHeader().setDefaultSectionSize(100)
        self.Search_Display_Results_Table.horizontalHeader().setMinimumSectionSize(200)
        self.Search_Display_Results_Table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.Search_Display_Results_Table)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Search_Display_Help_Button = QtWidgets.QPushButton(self.Search_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search_Display_Help_Button.sizePolicy().hasHeightForWidth())
        self.Search_Display_Help_Button.setSizePolicy(sizePolicy)
        self.Search_Display_Help_Button.setMinimumSize(QtCore.QSize(242, 50))
        self.Search_Display_Help_Button.setMaximumSize(QtCore.QSize(100, 50))
        self.Search_Display_Help_Button.setStyleSheet("QPushButton#Search_Display_Help_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Search_Display_Help_Button:pressed {\n"
"background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Search_Display_Help_Button.setObjectName("Search_Display_Help_Button")
        self.horizontalLayout_3.addWidget(self.Search_Display_Help_Button)
        spacerItem8 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.Search_Print_PDF_Button = QtWidgets.QPushButton(self.Search_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search_Print_PDF_Button.sizePolicy().hasHeightForWidth())
        self.Search_Print_PDF_Button.setSizePolicy(sizePolicy)
        self.Search_Print_PDF_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.Search_Print_PDF_Button.setStyleSheet("QPushButton#Search_Print_PDF_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Search_Print_PDF_Button:pressed {\n"
"background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Search_Print_PDF_Button.setObjectName("Search_Print_PDF_Button")
        self.horizontalLayout_3.addWidget(self.Search_Print_PDF_Button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.Admin_Select.addTab(self.Search_Tab, "")
        self.Edit_Tab = QtWidgets.QWidget()
        self.Edit_Tab.setObjectName("Edit_Tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Edit_Tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 3, 2, 1, 1)
        self.Edit_Assign_To_Label = QtWidgets.QLabel(self.Edit_Tab)
        self.Edit_Assign_To_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Edit_Assign_To_Label.setObjectName("Edit_Assign_To_Label")
        self.gridLayout_2.addWidget(self.Edit_Assign_To_Label, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 0, 3, 1, 1)
        self.Edit_AssignTo_Field = QtWidgets.QLineEdit(self.Edit_Tab)
        self.Edit_AssignTo_Field.setMinimumSize(QtCore.QSize(250, 30))
        self.Edit_AssignTo_Field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Edit_AssignTo_Field.setObjectName("Edit_AssignTo_Field")
        self.gridLayout_2.addWidget(self.Edit_AssignTo_Field, 1, 2, 1, 1)
        self.Edit_Asset_Field = QtWidgets.QLineEdit(self.Edit_Tab)
        self.Edit_Asset_Field.setMinimumSize(QtCore.QSize(250, 30))
        self.Edit_Asset_Field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Edit_Asset_Field.setText("")
        self.Edit_Asset_Field.setObjectName("Edit_Asset_Field")
        self.gridLayout_2.addWidget(self.Edit_Asset_Field, 0, 2, 1, 1)
        self.Edit_UI_Message_Name_From_ID = QtWidgets.QLabel(self.Edit_Tab)
        self.Edit_UI_Message_Name_From_ID.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Edit_UI_Message_Name_From_ID.setText("")
        self.Edit_UI_Message_Name_From_ID.setObjectName("Edit_UI_Message_Name_From_ID")
        self.gridLayout_2.addWidget(self.Edit_UI_Message_Name_From_ID, 1, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 1, 1, 1)
        self.Edit_Clear_Button = QtWidgets.QPushButton(self.Edit_Tab)
        self.Edit_Clear_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.Edit_Clear_Button.setStyleSheet("QPushButton#Edit_Clear_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Edit_Clear_Button:pressed {\n"
"background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Edit_Clear_Button.setObjectName("Edit_Clear_Button")
        self.gridLayout_2.addWidget(self.Edit_Clear_Button, 1, 5, 1, 1)
        self.Edit_Commit_Edits_Button = QtWidgets.QPushButton(self.Edit_Tab)
        self.Edit_Commit_Edits_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.Edit_Commit_Edits_Button.setStyleSheet("QPushButton#Edit_Commit_Edits_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Edit_Commit_Edits_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Edit_Commit_Edits_Button.setObjectName("Edit_Commit_Edits_Button")
        self.gridLayout_2.addWidget(self.Edit_Commit_Edits_Button, 2, 5, 1, 1)
        self.Edit_Update_Status_Label = QtWidgets.QLabel(self.Edit_Tab)
        self.Edit_Update_Status_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Edit_Update_Status_Label.setObjectName("Edit_Update_Status_Label")
        self.gridLayout_2.addWidget(self.Edit_Update_Status_Label, 2, 0, 1, 1)
        self.Edit_Asset_Label = QtWidgets.QLabel(self.Edit_Tab)
        self.Edit_Asset_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Edit_Asset_Label.setObjectName("Edit_Asset_Label")
        self.gridLayout_2.addWidget(self.Edit_Asset_Label, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 9, 2, 1, 1)
        self.Edit_UI_Message_Prompt = QtWidgets.QLabel(self.Edit_Tab)
        self.Edit_UI_Message_Prompt.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Edit_UI_Message_Prompt.setText("")
        self.Edit_UI_Message_Prompt.setObjectName("Edit_UI_Message_Prompt")
        self.gridLayout_2.addWidget(self.Edit_UI_Message_Prompt, 2, 3, 1, 1)
        self.Edit_Update_Status_Dropdown = QtWidgets.QComboBox(self.Edit_Tab)
        self.Edit_Update_Status_Dropdown.setMinimumSize(QtCore.QSize(250, 30))
        self.Edit_Update_Status_Dropdown.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Edit_Update_Status_Dropdown.setEditable(True)
        self.Edit_Update_Status_Dropdown.setObjectName("Edit_Update_Status_Dropdown")
        self.Edit_Update_Status_Dropdown.addItem("")
        self.Edit_Update_Status_Dropdown.setItemText(0, "")
        self.Edit_Update_Status_Dropdown.addItem("")
        self.Edit_Update_Status_Dropdown.addItem("")
        self.Edit_Update_Status_Dropdown.addItem("")
        self.Edit_Update_Status_Dropdown.addItem("")
        self.Edit_Update_Status_Dropdown.addItem("")
        self.Edit_Update_Status_Dropdown.addItem("")
        self.Edit_Update_Status_Dropdown.addItem("")
        self.gridLayout_2.addWidget(self.Edit_Update_Status_Dropdown, 2, 2, 1, 1)
        self.Edit_Display_Help_Button = QtWidgets.QPushButton(self.Edit_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Edit_Display_Help_Button.sizePolicy().hasHeightForWidth())
        self.Edit_Display_Help_Button.setSizePolicy(sizePolicy)
        self.Edit_Display_Help_Button.setMinimumSize(QtCore.QSize(242, 50))
        self.Edit_Display_Help_Button.setMaximumSize(QtCore.QSize(100, 50))
        self.Edit_Display_Help_Button.setStyleSheet("QPushButton#Edit_Display_Help_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Edit_Display_Help_Button:pressed {\n"
"background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Edit_Display_Help_Button.setObjectName("Edit_Display_Help_Button")
        self.gridLayout_2.addWidget(self.Edit_Display_Help_Button, 9, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem13, 7, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem14, 6, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 5, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem16, 8, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem17, 4, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.Admin_Select.addTab(self.Edit_Tab, "")
        self.Create_Tab = QtWidgets.QWidget()
        self.Create_Tab.setObjectName("Create_Tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Create_Tab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Create_Clear_Fields_Button = QtWidgets.QPushButton(self.Create_Tab)
        self.Create_Clear_Fields_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.Create_Clear_Fields_Button.setStyleSheet("QPushButton#Create_Clear_Fields_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Create_Clear_Fields_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Create_Clear_Fields_Button.setObjectName("Create_Clear_Fields_Button")
        self.verticalLayout_8.addWidget(self.Create_Clear_Fields_Button)
        self.Create_Confirm_Entry_Button = QtWidgets.QPushButton(self.Create_Tab)
        self.Create_Confirm_Entry_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.Create_Confirm_Entry_Button.setStyleSheet("QPushButton#Create_Confirm_Entry_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Create_Confirm_Entry_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Create_Confirm_Entry_Button.setObjectName("Create_Confirm_Entry_Button")
        self.verticalLayout_8.addWidget(self.Create_Confirm_Entry_Button)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem18)
        self.Import_ImportEmployees_Button = QtWidgets.QPushButton(self.Create_Tab)
        self.Import_ImportEmployees_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.Import_ImportEmployees_Button.setStyleSheet("QPushButton#Import_ImportEmployees_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Import_ImportEmployees_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Import_ImportEmployees_Button.setObjectName("Import_ImportEmployees_Button")
        self.verticalLayout_8.addWidget(self.Import_ImportEmployees_Button)
        self.Import_ImportAssets_Button = QtWidgets.QPushButton(self.Create_Tab)
        self.Import_ImportAssets_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.Import_ImportAssets_Button.setStyleSheet("QPushButton#Import_ImportAssets_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Import_ImportAssets_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Import_ImportAssets_Button.setObjectName("Import_ImportAssets_Button")
        self.verticalLayout_8.addWidget(self.Import_ImportAssets_Button)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem19)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem20)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem21)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem22)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem23)
        self.gridLayout_6.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem24, 0, 1, 1, 1)
        self.Create_Asset_Num_Field = QtWidgets.QLineEdit(self.Create_Tab)
        self.Create_Asset_Num_Field.setMinimumSize(QtCore.QSize(250, 30))
        self.Create_Asset_Num_Field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Create_Asset_Num_Field.setObjectName("Create_Asset_Num_Field")
        self.gridLayout_5.addWidget(self.Create_Asset_Num_Field, 0, 2, 1, 1)
        self.Create_Asset_Num_Label = QtWidgets.QLabel(self.Create_Tab)
        self.Create_Asset_Num_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Create_Asset_Num_Label.setObjectName("Create_Asset_Num_Label")
        self.gridLayout_5.addWidget(self.Create_Asset_Num_Label, 0, 0, 1, 1)
        self.Create_UI_Message_Prompt = QtWidgets.QLabel(self.Create_Tab)
        self.Create_UI_Message_Prompt.setMinimumSize(QtCore.QSize(0, 51))
        self.Create_UI_Message_Prompt.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Create_UI_Message_Prompt.setText("")
        self.Create_UI_Message_Prompt.setObjectName("Create_UI_Message_Prompt")
        self.gridLayout_5.addWidget(self.Create_UI_Message_Prompt, 8, 2, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem25, 0, 3, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem26, 1, 2, 1, 1)
        self.Create_Display_Help_Button = QtWidgets.QPushButton(self.Create_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Create_Display_Help_Button.sizePolicy().hasHeightForWidth())
        self.Create_Display_Help_Button.setSizePolicy(sizePolicy)
        self.Create_Display_Help_Button.setMinimumSize(QtCore.QSize(242, 50))
        self.Create_Display_Help_Button.setMaximumSize(QtCore.QSize(100, 50))
        self.Create_Display_Help_Button.setStyleSheet("QPushButton#Create_Display_Help_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Create_Display_Help_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.Create_Display_Help_Button.setObjectName("Create_Display_Help_Button")
        self.gridLayout_5.addWidget(self.Create_Display_Help_Button, 8, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_6)
        self.Admin_Select.addTab(self.Create_Tab, "")
        self.Assign_Tag_Tab = QtWidgets.QWidget()
        self.Assign_Tag_Tab.setObjectName("Assign_Tag_Tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Assign_Tag_Tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.AssignTag_Clear_Fields_Button = QtWidgets.QPushButton(self.Assign_Tag_Tab)
        self.AssignTag_Clear_Fields_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.AssignTag_Clear_Fields_Button.setStyleSheet("QPushButton#AssignTag_Clear_Fields_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#AssignTag_Clear_Fields_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.AssignTag_Clear_Fields_Button.setObjectName("AssignTag_Clear_Fields_Button")
        self.verticalLayout_9.addWidget(self.AssignTag_Clear_Fields_Button)
        self.AssignTag_Confirm_Entry_Button = QtWidgets.QPushButton(self.Assign_Tag_Tab)
        self.AssignTag_Confirm_Entry_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.AssignTag_Confirm_Entry_Button.setStyleSheet("QPushButton#AssignTag_Confirm_Entry_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#AssignTag_Confirm_Entry_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.AssignTag_Confirm_Entry_Button.setObjectName("AssignTag_Confirm_Entry_Button")
        self.verticalLayout_9.addWidget(self.AssignTag_Confirm_Entry_Button)
        self.AssignTag_Remove_Tag_Button = QtWidgets.QPushButton(self.Assign_Tag_Tab)
        self.AssignTag_Remove_Tag_Button.setMinimumSize(QtCore.QSize(242, 51))
        self.AssignTag_Remove_Tag_Button.setStyleSheet("QPushButton#AssignTag_Remove_Tag_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#AssignTag_Remove_Tag_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.AssignTag_Remove_Tag_Button.setObjectName("AssignTag_Remove_Tag_Button")
        self.verticalLayout_9.addWidget(self.AssignTag_Remove_Tag_Button)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem27)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem28)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem29)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem30)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem31)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem32)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem33)
        self.gridLayout_7.addLayout(self.verticalLayout_9, 0, 1, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem34, 0, 3, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem35, 0, 1, 1, 1)
        self.AssignTag_Asset_Num_Field = QtWidgets.QLineEdit(self.Assign_Tag_Tab)
        self.AssignTag_Asset_Num_Field.setMinimumSize(QtCore.QSize(250, 30))
        self.AssignTag_Asset_Num_Field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.AssignTag_Asset_Num_Field.setObjectName("AssignTag_Asset_Num_Field")
        self.gridLayout_8.addWidget(self.AssignTag_Asset_Num_Field, 0, 2, 1, 1)
        self.AssignTag_RFID_Tag_Label = QtWidgets.QLabel(self.Assign_Tag_Tab)
        self.AssignTag_RFID_Tag_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.AssignTag_RFID_Tag_Label.setObjectName("AssignTag_RFID_Tag_Label")
        self.gridLayout_8.addWidget(self.AssignTag_RFID_Tag_Label, 1, 0, 1, 1)
        self.AssignTag_RFID_Tag_Field = QtWidgets.QLineEdit(self.Assign_Tag_Tab)
        self.AssignTag_RFID_Tag_Field.setMinimumSize(QtCore.QSize(250, 30))
        self.AssignTag_RFID_Tag_Field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: #282c30;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.AssignTag_RFID_Tag_Field.setText("")
        self.AssignTag_RFID_Tag_Field.setObjectName("AssignTag_RFID_Tag_Field")
        self.gridLayout_8.addWidget(self.AssignTag_RFID_Tag_Field, 1, 2, 1, 1)
        self.AssignTag_Asset_Num_Label = QtWidgets.QLabel(self.Assign_Tag_Tab)
        self.AssignTag_Asset_Num_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.AssignTag_Asset_Num_Label.setObjectName("AssignTag_Asset_Num_Label")
        self.gridLayout_8.addWidget(self.AssignTag_Asset_Num_Label, 0, 0, 1, 1)
        self.AssignTag_Display_Help_Button = QtWidgets.QPushButton(self.Assign_Tag_Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AssignTag_Display_Help_Button.sizePolicy().hasHeightForWidth())
        self.AssignTag_Display_Help_Button.setSizePolicy(sizePolicy)
        self.AssignTag_Display_Help_Button.setMinimumSize(QtCore.QSize(242, 50))
        self.AssignTag_Display_Help_Button.setMaximumSize(QtCore.QSize(100, 50))
        self.AssignTag_Display_Help_Button.setStyleSheet("QPushButton#AssignTag_Display_Help_Button {\n"
"background-color: #282c30;\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#AssignTag_Display_Help_Button:pressed {\n"
"    background-color: #577590;\n"
"    border-style: inset;\n"
"}")
        self.AssignTag_Display_Help_Button.setObjectName("AssignTag_Display_Help_Button")
        self.gridLayout_8.addWidget(self.AssignTag_Display_Help_Button, 4, 0, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem36, 2, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_7)
        self.Admin_Select.addTab(self.Assign_Tag_Tab, "")
        self.Resolve_Tab = QtWidgets.QWidget()
        self.Resolve_Tab.setObjectName("Resolve_Tab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Resolve_Tab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Resolve_Display_Conflicts_Table = QtWidgets.QTableWidget(self.Resolve_Tab)
        self.Resolve_Display_Conflicts_Table.setObjectName("Resolve_Display_Conflicts_Table")
        self.Resolve_Display_Conflicts_Table.setColumnCount(6)
        self.Resolve_Display_Conflicts_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Resolve_Display_Conflicts_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Resolve_Display_Conflicts_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Resolve_Display_Conflicts_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Resolve_Display_Conflicts_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Resolve_Display_Conflicts_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Resolve_Display_Conflicts_Table.setHorizontalHeaderItem(5, item)
        self.verticalLayout_12.addWidget(self.Resolve_Display_Conflicts_Table)
        self.pushButton = QtWidgets.QPushButton(self.Resolve_Tab)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_12.addWidget(self.pushButton)
        self.Admin_Select.addTab(self.Resolve_Tab, "")
        self.verticalLayout_6.addWidget(self.Admin_Select)

        self.retranslateUi(Admin_Interface)
        self.Admin_Select.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Admin_Interface)
        Admin_Interface.setTabOrder(self.Home_ChangePassword_Button, self.Search_Datetime_From)
        Admin_Interface.setTabOrder(self.Search_Datetime_From, self.Search_Datetime_To)
        Admin_Interface.setTabOrder(self.Search_Datetime_To, self.Search_Month_By_Month_Search_Dropdown)
        Admin_Interface.setTabOrder(self.Search_Month_By_Month_Search_Dropdown, self.Search_Employee_ID_Entry_Field)
        Admin_Interface.setTabOrder(self.Search_Employee_ID_Entry_Field, self.Search_Display_Results_Table)
        Admin_Interface.setTabOrder(self.Search_Display_Results_Table, self.Search_Print_PDF_Button)
        Admin_Interface.setTabOrder(self.Search_Print_PDF_Button, self.Edit_Asset_Field)
        Admin_Interface.setTabOrder(self.Edit_Asset_Field, self.Create_Asset_Num_Field)
        Admin_Interface.setTabOrder(self.Create_Asset_Num_Field, self.Resolve_Display_Conflicts_Table)
        Admin_Interface.setTabOrder(self.Resolve_Display_Conflicts_Table, self.pushButton)

    def retranslateUi(self, Admin_Interface):
        _translate = QtCore.QCoreApplication.translate
        Admin_Interface.setWindowTitle(_translate("Admin_Interface", "Form"))
        self.Home_Welcome_Message.setText(_translate("Admin_Interface", "Welcome to Admin Access"))
        self.label.setText(_translate("Admin_Interface", "Select Tabs Above To Navigate"))
        self.Home_ChangePassword_Button.setText(_translate("Admin_Interface", "Change Password"))
        self.Admin_Select.setTabText(self.Admin_Select.indexOf(self.Home_Tab), _translate("Admin_Interface", "Home"))
        self.Search_SearchAsset_Query_Button.setText(_translate("Admin_Interface", "Search"))
        self.Search_Reset_Fields_Button.setText(_translate("Admin_Interface", "Reset Filters"))
        self.Search_Asset_Num_From_Label.setText(_translate("Admin_Interface", "Asset ID(s):"))
        self.Search_Datetime_From.setDisplayFormat(_translate("Admin_Interface", "MMM d yyyy"))
        self.Search_Datetime_To.setDisplayFormat(_translate("Admin_Interface", "MMM d yyyy"))
        self.Search_Employee_ID_Label.setText(_translate("Admin_Interface", "Employee ID:"))
        self.Search_Datetime_To_Label.setText(_translate("Admin_Interface", "Date/Time To:"))
        self.Search_Filters_Title.setText(_translate("Admin_Interface", "Search Filters"))
        self.Search_Datetime_From_Label.setText(_translate("Admin_Interface", "Date/Time From:"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(1, _translate("Admin_Interface", "Jan"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(2, _translate("Admin_Interface", "Feb"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(3, _translate("Admin_Interface", "Mar"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(4, _translate("Admin_Interface", "Apr"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(5, _translate("Admin_Interface", "May"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(6, _translate("Admin_Interface", "Jun"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(7, _translate("Admin_Interface", "Jul"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(8, _translate("Admin_Interface", "Aug"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(9, _translate("Admin_Interface", "Sep"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(10, _translate("Admin_Interface", "Oct"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(11, _translate("Admin_Interface", "Nov"))
        self.Search_Month_By_Month_Search_Dropdown.setItemText(12, _translate("Admin_Interface", "Dec"))
        self.Search_Month_by_Month_Label.setText(_translate("Admin_Interface", "Month by Month:"))
        self.Search_Display_Results_Table.setSortingEnabled(True)
        item = self.Search_Display_Results_Table.horizontalHeaderItem(0)
        item.setText(_translate("Admin_Interface", "Asset ID"))
        item = self.Search_Display_Results_Table.horizontalHeaderItem(1)
        item.setText(_translate("Admin_Interface", "Employee ID"))
        item = self.Search_Display_Results_Table.horizontalHeaderItem(2)
        item.setText(_translate("Admin_Interface", "Status"))
        item = self.Search_Display_Results_Table.horizontalHeaderItem(3)
        item.setText(_translate("Admin_Interface", "Timestamp"))
        self.Search_Display_Help_Button.setText(_translate("Admin_Interface", "Help"))
        self.Search_Print_PDF_Button.setText(_translate("Admin_Interface", "Print to PDF"))
        self.Admin_Select.setTabText(self.Admin_Select.indexOf(self.Search_Tab), _translate("Admin_Interface", "Search"))
        self.Edit_Assign_To_Label.setText(_translate("Admin_Interface", "Assign To:"))
        self.Edit_Clear_Button.setText(_translate("Admin_Interface", "Clear"))
        self.Edit_Commit_Edits_Button.setText(_translate("Admin_Interface", "Commit Edits"))
        self.Edit_Update_Status_Label.setText(_translate("Admin_Interface", "Update Status:"))
        self.Edit_Asset_Label.setText(_translate("Admin_Interface", "Asset ID:"))
        self.Edit_Update_Status_Dropdown.setItemText(1, _translate("Admin_Interface", "Checked In"))
        self.Edit_Update_Status_Dropdown.setItemText(2, _translate("Admin_Interface", "Checked Out"))
        self.Edit_Update_Status_Dropdown.setItemText(3, _translate("Admin_Interface", "In Repair"))
        self.Edit_Update_Status_Dropdown.setItemText(4, _translate("Admin_Interface", "Retired"))
        self.Edit_Update_Status_Dropdown.setItemText(5, _translate("Admin_Interface", "Broken"))
        self.Edit_Update_Status_Dropdown.setItemText(6, _translate("Admin_Interface", "New Item"))
        self.Edit_Update_Status_Dropdown.setItemText(7, _translate("Admin_Interface", "New employee"))
        self.Edit_Display_Help_Button.setText(_translate("Admin_Interface", "Help"))
        self.Admin_Select.setTabText(self.Admin_Select.indexOf(self.Edit_Tab), _translate("Admin_Interface", "Edit"))
        self.Create_Clear_Fields_Button.setText(_translate("Admin_Interface", "Clear Fields"))
        self.Create_Confirm_Entry_Button.setText(_translate("Admin_Interface", "Enter"))
        self.Import_ImportEmployees_Button.setText(_translate("Admin_Interface", "Import Employees from .xlsx file"))
        self.Import_ImportAssets_Button.setText(_translate("Admin_Interface", "Import Assets from .xlsx file"))
        self.Create_Asset_Num_Label.setText(_translate("Admin_Interface", "Asset ID:"))
        self.Create_Display_Help_Button.setText(_translate("Admin_Interface", "Help"))
        self.Admin_Select.setTabText(self.Admin_Select.indexOf(self.Create_Tab), _translate("Admin_Interface", "Create"))
        self.AssignTag_Clear_Fields_Button.setText(_translate("Admin_Interface", "Clear Fields"))
        self.AssignTag_Confirm_Entry_Button.setText(_translate("Admin_Interface", "Assign Tag to Asset"))
        self.AssignTag_Remove_Tag_Button.setText(_translate("Admin_Interface", "Remove Tag from Asset"))
        self.AssignTag_RFID_Tag_Label.setText(_translate("Admin_Interface", "RFID Tag #:"))
        self.AssignTag_Asset_Num_Label.setText(_translate("Admin_Interface", "Asset ID:"))
        self.AssignTag_Display_Help_Button.setText(_translate("Admin_Interface", "Help"))
        self.Admin_Select.setTabText(self.Admin_Select.indexOf(self.Assign_Tag_Tab), _translate("Admin_Interface", "Assign Tag"))
        item = self.Resolve_Display_Conflicts_Table.horizontalHeaderItem(0)
        item.setText(_translate("Admin_Interface", "Asset #"))
        item = self.Resolve_Display_Conflicts_Table.horizontalHeaderItem(1)
        item.setText(_translate("Admin_Interface", "RFID #"))
        item = self.Resolve_Display_Conflicts_Table.horizontalHeaderItem(2)
        item.setText(_translate("Admin_Interface", "Employee ID"))
        item = self.Resolve_Display_Conflicts_Table.horizontalHeaderItem(3)
        item.setText(_translate("Admin_Interface", "Date checked out"))
        item = self.Resolve_Display_Conflicts_Table.horizontalHeaderItem(4)
        item.setText(_translate("Admin_Interface", "Date checked in"))
        item = self.Resolve_Display_Conflicts_Table.horizontalHeaderItem(5)
        item.setText(_translate("Admin_Interface", "Conflict Msg"))
        self.pushButton.setText(_translate("Admin_Interface", "Conflict Details"))
        self.Admin_Select.setTabText(self.Admin_Select.indexOf(self.Resolve_Tab), _translate("Admin_Interface", "Resolve"))
