# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Error_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error_Window(object):
    def setupUi(self, Error_Window):
        Error_Window.setObjectName("Error_Window")
        Error_Window.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Error_Window)
        self.pushButton.setGeometry(QtCore.QRect(100, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Error_Window)
        self.label.setGeometry(QtCore.QRect(100, 80, 47, 13))
        self.label.setObjectName("label")

        self.retranslateUi(Error_Window)
        QtCore.QMetaObject.connectSlotsByName(Error_Window)

    def retranslateUi(self, Error_Window):
        _translate = QtCore.QCoreApplication.translate
        Error_Window.setWindowTitle(_translate("Error_Window", "Form"))
        self.pushButton.setText(_translate("Error_Window", "OK"))
        self.label.setText(_translate("Error_Window", "Error"))