# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Etek_main_window_All_In_One.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1025, 769)
        Form.setStyleSheet("background-color: rgb(0, 0, 52);")
        self.Equipment_List = QtWidgets.QTableWidget(Form)
        self.Equipment_List.setGeometry(QtCore.QRect(50, 250, 851, 401))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Equipment_List.sizePolicy().hasHeightForWidth())
        self.Equipment_List.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Equipment_List.setFont(font)
        self.Equipment_List.setStyleSheet("\n"
"QHeaderView::section\n"
"{\n"
"spacing: 10px;\n"
"background-color:lightblue;\n"
"color: white;\n"
"border: 1px solid red;\n"
"margin: 1px;\n"
"text-align: right;\n"
"font-family: arial;\n"
"font-size:12px;\n"
"}\n"
"\n"
"QTableWidget::section\n"
"{\n"
"\n"
"background-color: rgb(78, 78, 78);\n"
"}")
        self.Equipment_List.setObjectName("Equipment_List")
        self.Equipment_List.setColumnCount(1)
        self.Equipment_List.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Equipment_List.setHorizontalHeaderItem(0, item)
        self.Instruction_Label = QtWidgets.QLabel(Form)
        self.Instruction_Label.setGeometry(QtCore.QRect(100, 200, 701, 41))
        self.Instruction_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.Instruction_Label.setObjectName("Instruction_Label")
        self.Admin_Button = QtWidgets.QPushButton(Form)
        self.Admin_Button.setGeometry(QtCore.QRect(0, 0, 436, 51))
        self.Admin_Button.setStyleSheet("QPushButton#Admin_Button {\n"
"background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Admin_Button:pressed {\n"
"    background-color: rgb(0, 0, 80);\n"
"    border-style: inset;\n"
"}")
        self.Admin_Button.setObjectName("Admin_Button")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 100, 901, 46))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ID_Label = QtWidgets.QLabel(self.widget)
        self.ID_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"")
        self.ID_Label.setObjectName("ID_Label")
        self.horizontalLayout_3.addWidget(self.ID_Label)
        self.Manual_Entry_Field_2 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Manual_Entry_Field_2.sizePolicy().hasHeightForWidth())
        self.Manual_Entry_Field_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Manual_Entry_Field_2.setFont(font)
        self.Manual_Entry_Field_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(78, 78, 78);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
" border-radius: 10px;")
        self.Manual_Entry_Field_2.setObjectName("Manual_Entry_Field_2")
        self.horizontalLayout_3.addWidget(self.Manual_Entry_Field_2)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(50, 650, 851, 115))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Cancel_Button = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cancel_Button.sizePolicy().hasHeightForWidth())
        self.Cancel_Button.setSizePolicy(sizePolicy)
        self.Cancel_Button.setMinimumSize(QtCore.QSize(208, 113))
        self.Cancel_Button.setMaximumSize(QtCore.QSize(208, 113))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Cancel_Button.setFont(font)
        self.Cancel_Button.setStyleSheet("QPushButton#Cancel_Button {\n"
"background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Cancel_Button:pressed {\n"
"    background-color: rgb(0, 0, 80);\n"
"    border-style: inset;\n"
"}")
        self.Cancel_Button.setObjectName("Cancel_Button")
        self.horizontalLayout.addWidget(self.Cancel_Button)
        self.Finish_Button = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Finish_Button.sizePolicy().hasHeightForWidth())
        self.Finish_Button.setSizePolicy(sizePolicy)
        self.Finish_Button.setMinimumSize(QtCore.QSize(208, 113))
        self.Finish_Button.setMaximumSize(QtCore.QSize(208, 113))
        self.Finish_Button.setBaseSize(QtCore.QSize(16, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Finish_Button.setFont(font)
        self.Finish_Button.setStyleSheet("QPushButton#Finish_Button {\n"
"background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Finish_Button:pressed {\n"
"    background-color: rgb(0, 0, 80);\n"
"    border-style: inset;\n"
"}")
        self.Finish_Button.setObjectName("Finish_Button")
        self.horizontalLayout.addWidget(self.Finish_Button)
        self.Check_Out_Button = QtWidgets.QPushButton(self.widget1)
        self.Check_Out_Button.setMinimumSize(QtCore.QSize(208, 113))
        self.Check_Out_Button.setMaximumSize(QtCore.QSize(208, 113))
        self.Check_Out_Button.setStyleSheet("QPushButton#Check_Out_Button {\n"
"background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton#Check_Out_Button:pressed {\n"
"    background-color: rgb(0, 0, 80);\n"
"    border-style: inset;\n"
"}")
        self.Check_Out_Button.setObjectName("Check_Out_Button")
        self.horizontalLayout.addWidget(self.Check_Out_Button)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(1, 151, 901, 46))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Manual_Entry_Field = QtWidgets.QLineEdit(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Manual_Entry_Field.sizePolicy().hasHeightForWidth())
        self.Manual_Entry_Field.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Manual_Entry_Field.setFont(font)
        self.Manual_Entry_Field.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(78, 78, 78);\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
" border-radius: 10px;")
        self.Manual_Entry_Field.setObjectName("Manual_Entry_Field")
        self.horizontalLayout_2.addWidget(self.Manual_Entry_Field)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.Equipment_List.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Asset #"))
        self.Instruction_Label.setText(_translate("Form", "Scan items or enter asset # above to check-in or check-out"))
        self.Admin_Button.setText(_translate("Form", "Admin Access"))
        self.ID_Label.setText(_translate("Form", "Please enter Employee ID"))
        self.Cancel_Button.setText(_translate("Form", "Cancel"))
        self.Finish_Button.setText(_translate("Form", "Check-In"))
        self.Check_Out_Button.setText(_translate("Form", "Check-Out"))
        self.label_2.setText(_translate("Form", "Asset #:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
