# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Etek_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Check_out_button = QtWidgets.QPushButton(self.centralwidget)
        self.Check_out_button.setGeometry(QtCore.QRect(400, 290, 380, 251))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.Check_out_button.setFont(font)
        self.Check_out_button.setObjectName("Check_out_button")
        self.Check_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.Check_in_button.setGeometry(QtCore.QRect(10, 290, 380, 251))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.Check_in_button.setFont(font)
        self.Check_in_button.setObjectName("Check_in_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 721, 131))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.Employee_ID_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Employee_ID_input.setGeometry(QtCore.QRect(270, 180, 291, 61))
        self.Employee_ID_input.setObjectName("Employee_ID_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 190, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Check_out_button.setText(_translate("MainWindow", "CHECK-OUT"))
        self.Check_in_button.setText(_translate("MainWindow", "CHECK-IN"))
        self.label.setText(_translate("MainWindow", "Welcome to E-TEK, please enter or scan your employee ID, and select your desired action."))
        self.label_2.setText(_translate("MainWindow", "Employee ID:"))
