# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_window_widget2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 468)
        self.Check_In_button = QtWidgets.QPushButton(MainWindow)
        self.Check_In_button.setGeometry(QtCore.QRect(94, 160, 331, 211))
        self.Check_In_button.setObjectName("Check_In_button")
        self.Check_out_button = QtWidgets.QPushButton(MainWindow)
        self.Check_out_button.setGeometry(QtCore.QRect(450, 160, 321, 211))
        self.Check_out_button.setObjectName("Check_out_button")
        self.Employee_ID_input = QtWidgets.QLineEdit(MainWindow)
        self.Employee_ID_input.setGeometry(QtCore.QRect(280, 80, 113, 20))
        self.Employee_ID_input.setObjectName("Employee_ID_input")
        self.Employee_ID_label = QtWidgets.QLabel(MainWindow)
        self.Employee_ID_label.setGeometry(QtCore.QRect(130, 80, 47, 13))
        self.Employee_ID_label.setObjectName("Employee_ID_label")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.Check_In_button.setText(_translate("MainWindow", "Check In"))
        self.Check_out_button.setText(_translate("MainWindow", "Check Out"))
        self.Employee_ID_label.setText(_translate("MainWindow", "EmployeeID"))
